name: daraja.js-ci-workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_KEY: ${{secrets.APP_KEY}}
      APP_SECRET: ${{secrets.APP_SECRET}}
      LNM_PASSKEY: ${{secrets.LNM_PASSKEY}}
      DEBUG: true

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Configure pnpm
        shell: bash
        run: |
          pnpm config set git-checks false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # Cache pnpm output
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm ci
      - run: pnpm fmt:check
      - run: pnpm test -- --coverage
        env:
          CI: true
      - run: pnpm build

      - name: Generate a release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Upload coverage reports to codecov
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
