name: daraja.js-ci-workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node-version: [14.x, 16.x, 18.x]
    runs-on: ubuntu-latest
    env:
      APP_KEY: ${{secrets.APP_KEY}}
      APP_SECRET: ${{secrets.APP_SECRET}}
      LNM_PASSKEY: ${{secrets.LNM_PASSKEY}}
      DEBUG: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Cache deps on unix
        if: ${{ runner.os}} != "windows"
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{runner.os}}-node-

      - name: Cache deps on windows
        if: ${{runner.os}} == "windows"
        uses: actions/cache@v2
        with:
          path: ~\AppData\Roaming\npm-cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{runner.os}}-node-

      - name: Upgrade NPM
        run: npm install -g npm

      - run: npm ci
      - run: npm run fmt:check
      - run: npm test -- --coverage
        env:
          CI: true

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
